### ISSUE TITLE
enveriment: warning C4819: 该文件包含不能在当前代码页(936)中表示的字符（已解决）查看终端乱码解决办法

### ISSUE THREAD

**Issue by wulalal1** [Sunrisepeak/d2ds#21]
### Describe the bug | 问题描述
error: cl: 命令行 warning D9002 :忽略未知选项“-std:c++11”
dslings.0.cpp
dslings\tests\dslings.0.cpp(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
.\common/common.hpp(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
dstruct\spec/DStructSpec.hpp(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失        
.\common/honly_logger.hpp(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
在执行xmake dslings出现的问题

**Comment by Sunrisepeak** [comment]
@wulalal1 这个应该是win平台的 中文字符 编码问题的警告

**Comment by wulalal1** [comment]
https://github.com/Sunrisepeak/d2ds/issues/2
解决地址在这里
