### ISSUE TITLE
代码需要提交两次

### ISSUE THREAD

**Issue by wulalal1** [Sunrisepeak/d2ds#22]
### Describe the bug | 问题描述
对于每次对应的头文件跳转到对应的文件中编写代码
跳转到这个"exercises/other/cpp-base/Template.hpp"文件里面编写完代码
直接进入这个里面 编写
![团](https://github.com/Sunrisepeak/d2ds/assets/101454967/b16389f4-77e7-42cf-9a67-3cb83788b480)
找准对应的目录之后编写则不出现问题
#ifndef TEMPLATE_HPP_D2DS
#define TEMPLATE_HPP_D2DS

namespace d2ds {
// show your code
template<typename T>
T max(T a, T b) {
    return a > b ? a : b;
};
template <typename T>
class Box{
    public:
    void set_value(const T &val){
        value = val;
    }
    const T &get_value() const{
        return value;
    }
    private:
    T value;

};
}

#endif
写完之后出现新的问题
![五](https://github.com/Sunrisepeak/d2ds/assets/101454967/857e6cd6-9e2b-47af-a07c-819b03ee0f9f)
明明定义完成了但是提示出现未定义但是能通过测试
![4](https://github.com/Sunrisepeak/d2ds/assets/101454967/4e5fb4df-73c5-4bcf-814e-92dfc34595f9)
现在则进入这个路径里面写代码
![3](https://github.com/Sunrisepeak/d2ds/assets/101454967/5ced8697-2f7e-4857-b6e3-db439e271580)

![Uploading 2.png…]()
则不出现这个问题

**Comment by Sunrisepeak** [comment]
-> #23
