### ISSUE TITLE
vscode 头文件跳转问题已解决（里面有终端乱码解决办法）

### ISSUE THREAD

**Issue by wulalal1** [Sunrisepeak/d2ds#23]
### Describe the bug | 问题描述
对于每次对应的头文件跳转到对应的文件中编写代码
跳转到这个"exercises/other/cpp-base/Template.hpp"文件里面编写完代码
直接进入这个里面 编写
![团](https://github.com/Sunrisepeak/d2ds/assets/101454967/b16389f4-77e7-42cf-9a67-3cb83788b480)
找准对应的目录之后编写则不出现问题
#ifndef TEMPLATE_HPP_D2DS
#define TEMPLATE_HPP_D2DS

namespace d2ds {
// show your code
template<typename T>
T max(T a, T b) {
    return a > b ? a : b;
};
template <typename T>
class Box{
    public:
    void set_value(const T &val){
        value = val;
    }
    const T &get_value() const{
        return value;
    }
    private:
    T value;

};
}

#endif
写完之后出现新的问题
![五](https://github.com/Sunrisepeak/d2ds/assets/101454967/857e6cd6-9e2b-47af-a07c-819b03ee0f9f)
明明定义完成了但是提示出现未定义但是能通过测试
![4](https://github.com/Sunrisepeak/d2ds/assets/101454967/4e5fb4df-73c5-4bcf-814e-92dfc34595f9)
现在则进入这个路径里面写代码
![3](https://github.com/Sunrisepeak/d2ds/assets/101454967/5ced8697-2f7e-4857-b6e3-db439e271580)

![Uploading 2.png…]()
则不出现这个问题

**Comment by Sunrisepeak** [comment]
@wulalal1 

![image](https://github.com/Sunrisepeak/d2ds/assets/38786181/b46088d7-e153-44f3-8da3-9ef734c16a1d)

这个提示是 代码编辑器的 问题。需要配置vscode 的C++ 环境。以及头文件查找路径

**Comment by Sunrisepeak** [comment]
@wulalal1 

![image](https://github.com/Sunrisepeak/d2ds/assets/38786181/f3f9babb-0f73-4c9e-8e61-0c23c1f5c874)

我看这个 表情输出 不乱码了。是解决乱码问题了吗

**Comment by wulalal1** [comment]
> @wulalal1
> 
> ![image](https://private-user-images.githubusercontent.com/38786181/341972853-f3f9babb-0f73-4c9e-8e61-0c23c1f5c874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjM1OTcsIm5iZiI6MTcxOTA2MzI5NywicGF0aCI6Ii8zODc4NjE4MS8zNDE5NzI4NTMtZjNmOWJhYmItMGY3My00YzllLThlNjEtMGMyM2MxZjVjODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MzQxYjdlZDljMjA4MTNjNzQxZWE1M2NhZWFhYzhkNWExZjE2YTBjYWY4MDZlNjRjOTdmZDhmYTE5NWI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2yDzPzwOmbV4hThFCXu3kyn3vjRNf8FQClNrv3MsPAI)
> 
> 我看这个 表情输出 不乱码了。是解决乱码问题了吗

是的全局设置UTF-8解决

**Comment by wulalal1** [comment]
> @wulalal1
> 
> ![image](https://private-user-images.githubusercontent.com/38786181/341971966-b46088d7-e153-44f3-8da3-9ef734c16a1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjM1OTcsIm5iZiI6MTcxOTA2MzI5NywicGF0aCI6Ii8zODc4NjE4MS8zNDE5NzE5NjYtYjQ2MDg4ZDctZTE1My00NGYzLThkYTMtOWVmNzM0YzE2YTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MTU0YWI1MTVlZWVlODFlNjg2M2ZkY2JkODgwYTg5Y2FiZTgxYzhkMTkyMTE3YTM3YTJkOTNjY2I5NDI4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sBejaJ3-VZ-573oBrU7QwxIMEzMr-Eom8VfTKCAz5OM)
> 
> 编译通过说明是没有问题的。 这个提示 不是编译器的功能, 是 代码编辑器(vs编辑器 / vscode / CLion / vim / qt creator / ...) 的功能。需要配置vscode 的C++ 代码插件。以及头文件查找路径

好的

**Comment by Sunrisepeak** [comment]
> > @wulalal1
> > ![image](https://private-user-images.githubusercontent.com/38786181/341972853-f3f9babb-0f73-4c9e-8e61-0c23c1f5c874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjM1OTcsIm5iZiI6MTcxOTA2MzI5NywicGF0aCI6Ii8zODc4NjE4MS8zNDE5NzI4NTMtZjNmOWJhYmItMGY3My00YzllLThlNjEtMGMyM2MxZjVjODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MzQxYjdlZDljMjA4MTNjNzQxZWE1M2NhZWFhYzhkNWExZjE2YTBjYWY4MDZlNjRjOTdmZDhmYTE5NWI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2yDzPzwOmbV4hThFCXu3kyn3vjRNf8FQClNrv3MsPAI)
> > 我看这个 表情输出 不乱码了。是解决乱码问题了吗
> 
> 是的全局设置UTF-8解决

帮忙补充一下, 设置步骤或方法(详细一点, 让初学者也能看懂) , 让后面遇到的同学也能有个参考

**Comment by Sunrisepeak** [comment]
@wulalal1 头文件路径配置已合并到仓库, 可以更新了
- #24

**Comment by wulalal1** [comment]
> > > @wulalal1
> > > ![image](https://private-user-images.githubusercontent.com/38786181/341972853-f3f9babb-0f73-4c9e-8e61-0c23c1f5c874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjM1OTcsIm5iZiI6MTcxOTA2MzI5NywicGF0aCI6Ii8zODc4NjE4MS8zNDE5NzI4NTMtZjNmOWJhYmItMGY3My00YzllLThlNjEtMGMyM2MxZjVjODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MzQxYjdlZDljMjA4MTNjNzQxZWE1M2NhZWFhYzhkNWExZjE2YTBjYWY4MDZlNjRjOTdmZDhmYTE5NWI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2yDzPzwOmbV4hThFCXu3kyn3vjRNf8FQClNrv3MsPAI)
> > > 我看这个 表情输出 不乱码了。是解决乱码问题了吗
> > 
> > 
> > 是的全局设置UTF-8解决
> 
> 帮忙补充一下, 设置步骤或方法(详细一点, 让初学者也能看懂) , 让后面遇到的同学也能有个参考

在setting里面搜encoding
![1](https://github.com/Sunrisepeak/d2ds/assets/101454967/a280e158-0c76-49a9-bc94-05946682a9eb)
然后在setting.json里面的C 和Cpp里面添加chcp  65001 &&
![2](https://github.com/Sunrisepeak/d2ds/assets/101454967/5e195e1e-2739-486d-b389-c4620ed84b0e)
之后重启就解决了

**Comment by wulalal1** [comment]
> > > @wulalal1
> > > ![image](https://private-user-images.githubusercontent.com/38786181/341972853-f3f9babb-0f73-4c9e-8e61-0c23c1f5c874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjM1OTcsIm5iZiI6MTcxOTA2MzI5NywicGF0aCI6Ii8zODc4NjE4MS8zNDE5NzI4NTMtZjNmOWJhYmItMGY3My00YzllLThlNjEtMGMyM2MxZjVjODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MzQxYjdlZDljMjA4MTNjNzQxZWE1M2NhZWFhYzhkNWExZjE2YTBjYWY4MDZlNjRjOTdmZDhmYTE5NWI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2yDzPzwOmbV4hThFCXu3kyn3vjRNf8FQClNrv3MsPAI)
> > > 我看这个 表情输出 不乱码了。是解决乱码问题了吗
> > 
> > 
> > 是的全局设置UTF-8解决
> 
> 帮忙补充一下, 设置步骤或方法(详细一点, 让初学者也能看懂) , 让后面遇到的同学也能有个参考

在setting里面搜encoding
![1](https://github.com/Sunrisepeak/d2ds/assets/101454967/a280e158-0c76-49a9-bc94-05946682a9eb)
然后在setting.json里面的C 和Cpp里面添加chcp  65001 &&
![2](https://github.com/Sunrisepeak/d2ds/assets/101454967/5e195e1e-2739-486d-b389-c4620ed84b0e)
之后重启就解决了

**Comment by Sunrisepeak** [comment]
@wulalal1 更新下, 看看头文件还有没有问题。如果没有问题, 可以把这个issue给关了
