### ISSUE TITLE
Features: windows平台的安装脚本(install.win.bat)中支持提示消息的颜色高亮

### ISSUE THREAD

**Issue by Sunrisepeak** [Sunrisepeak/d2ds#27]
## 功能描述

类似Linux平台的安装脚本输出提示信息显示不同颜色的/高亮的功能

## 预期效果

![Image](https://github.com/Sunrisepeak/d2ds/assets/38786181/e8574b64-6174-441a-afa0-5509dbf1d112)

## 代码实现

https://github.com/Sunrisepeak/d2ds/blob/3e8b7cc7769e0e2eeb3b4309ad25e474aaa8f90d/tools/install.unix.sh#L1-L41

https://github.com/Sunrisepeak/d2ds/blob/3e8b7cc7769e0e2eeb3b4309ad25e474aaa8f90d/tools/install.win.bat#L1-L41

## 可能的研究方向

- ansi color code
- windows cmd/powershell
- bat 脚本

## 相关链接

- https://ss64.com/nt/syntax-ansi.html

**Comment by sky-littlestar** [comment]
你好，我想试一试这个开发工作 @Sunrisepeak

**Comment by sky-littlestar** [comment]
我尝试直接用转义字符或者ctrl+[打出ESC符号都失败了，随后按照连接里的bat命令，实现了ESC符号的输出，但是我不太明白其中的原理，期望大家能够解惑以下，for /f %%i in ('echo prompt $E^| cmd') do set "ESC=%%i" 
为什么通过这句话，就能实现ESC字符对ESC的替代呢，该如何理解这句话呢？它是一个循环，然后给ESC赋一个字符串，里面的语句：
echo prompt $E^| cmd该怎么理解呢？
目前总体的实现效果如下：基本可以按照所需，对特定文本调色



![Image](https://github.com/Sunrisepeak/d2ds/assets/59217691/c1e4d005-1ea4-43d0-94d4-c4c2ddae26a5)
@Sunrisepeak

**Comment by Sunrisepeak** [comment]
> 我尝试直接用转义字符或者ctrl+[打出ESC符号都失败了，随后按照连接里的bat命令，实现了ESC符号的输出，但是我不太明白其中的原理，期望大家能够解惑以下，for /f %%i in ('echo prompt $E^| cmd') do set "ESC=%%i" 
> 为什么通过这句话，就能实现ESC字符对ESC的替代呢，该如何理解这句话呢？它是一个循环，然后给ESC赋一个字符串，里面的语句：
> echo prompt $E^| cmd该怎么理解呢？
> 目前总体的实现效果如下：基本可以按照所需，对特定文本调色
> 
> 
> 
> ![Image](https://github.com/Sunrisepeak/d2ds/assets/59217691/c1e4d005-1ea4-43d0-94d4-c4c2ddae26a5)
> @Sunrisepeak 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

可以把完整代码发一下，或把改动提个pr

**Comment by sky-littlestar** [comment]
> > 我尝试直接用转义字符或者ctrl+[打出ESC符号都失败了，随后按照连接里的bat命令，实现了ESC符号的输出，但是我不太明白其中的原理，期望大家能够解惑以下，for /f %%i in ('echo prompt $E^| cmd') do set "ESC=%%i"
> > 为什么通过这句话，就能实现ESC字符对ESC的替代呢，该如何理解这句话呢？它是一个循环，然后给ESC赋一个字符串，里面的语句：
> > echo prompt $E^| cmd该怎么理解呢？
> > 目前总体的实现效果如下：基本可以按照所需，对特定文本调色
> > ![Image](https://private-user-images.githubusercontent.com/59217691/346339989-c1e4d005-1ea4-43d0-94d4-c4c2ddae26a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTYxMzQsIm5iZiI6MTcyMDQ1NTgzNCwicGF0aCI6Ii81OTIxNzY5MS8zNDYzMzk5ODktYzFlNGQwMDUtMWVhNC00M2QwLTk0ZDQtYzRjMmRkYWUyNmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE2MjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwY2NlZjIyY2JiMWI3MDhjYzI5MmFjZWE0ZTU1MjVmMTZiYmUxYjRmZDk5YzEwZWU5OThlMzEwYWY5MWFjOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uUIlbMUC3wC9YAzSA2bAz5535ORLtLZ9HFIEEysT4Bo)
> > [@Sunrisepeak](https://github.com/Sunrisepeak)
> 
> 可以把完整代码发一下，或把改动提个pr

好的，网络今晚出了点问题，晚点我提个pr

**Comment by sky-littlestar** [comment]
> > 我尝试直接用转义字符或者ctrl+[打出ESC符号都失败了，随后按照连接里的bat命令，实现了ESC符号的输出，但是我不太明白其中的原理，期望大家能够解惑以下，for /f %%i in ('echo prompt $E^| cmd') do set "ESC=%%i"
> > 为什么通过这句话，就能实现ESC字符对ESC的替代呢，该如何理解这句话呢？它是一个循环，然后给ESC赋一个字符串，里面的语句：
> > echo prompt $E^| cmd该怎么理解呢？
> > 目前总体的实现效果如下：基本可以按照所需，对特定文本调色
> > ![Image](https://private-user-images.githubusercontent.com/59217691/346339989-c1e4d005-1ea4-43d0-94d4-c4c2ddae26a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTYzNzMsIm5iZiI6MTcyMDQ1NjA3MywicGF0aCI6Ii81OTIxNzY5MS8zNDYzMzk5ODktYzFlNGQwMDUtMWVhNC00M2QwLTk0ZDQtYzRjMmRkYWUyNmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE2Mjc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNmU3NTJmYjY2YWFjNDU1ZDYzYmQ4NjkxYTdlZmY5ZTgxZWMyZTczMThiYTRlYjMzNjFkZmUzM2U4OGQwYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Av5EVLcUYzVCZBTKvr2QxRXNZS-tEPIYXVbLEbn6aHk)
> > [@Sunrisepeak](https://github.com/Sunrisepeak)
> 
> 可以把完整代码发一下，或把改动提个pr

好的，今晚网络出了点问题，晚点我提个pr

**Comment by sky-littlestar** [comment]
提示消息颜色高亮基本上是实现功能了，但是目前有一个问题，在bat下，可供显示的颜色比较少，所以跟上面提供的示例样图有差异，这种色差的问题有什么办法解决吗？


![Image](https://github.com/user-attachments/assets/4fe9bb1d-c05d-48da-a835-fd9c8e3be9fc)

**Comment by Sunrisepeak** [comment]
> 提示消息颜色高亮基本上是实现功能了，但是目前有一个问题，在bat下，可供显示的颜色比较少，所以跟上面提供的示例样图有差异，这种色差的问题有什么办法解决吗？
> 
> ![Image](https://private-user-images.githubusercontent.com/59217691/358476770-4fe9bb1d-c05d-48da-a835-fd9c8e3be9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDQ2OTgsIm5iZiI6MTcyMzgwNDM5OCwicGF0aCI6Ii81OTIxNzY5MS8zNTg0NzY3NzAtNGZlOWJiMWQtYzA1ZC00OGRhLWE4MzUtZmQ5YzhlM2JlOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEwMzMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMWEzMDJmNGEzNDRhZDA1NTc0ZjgwMmE4YWY3NTIyNGU3YjAzNGFlMzM0YTQ1Mjg3MjI4N2E5Y2RlM2I5ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cO8-lG1UQUB1xsbJxbpBZZAxJtYBCV7wUVufGjzq_E8)
> 
> @Sunrisepeak

可以先提个PR, 然后我们基于PR讨论研究一下

**Comment by Sunrisepeak** [comment]
功能已合入 - https://github.com/Sunrisepeak/d2ds/pull/37
